import config from "../config.js";
const {tokenLifetimeInMinute} = config;
export const messageResponce = {
    entityNotFound: (entity) => `${entity} с указанным id не найден`,
    productBalance: (balance) => `Доступный остаток товара: ${balance}`,
    duplicateEmail: "Пользователь с указанным email уже зарегистрирован",
    duplicateProduct: "Не уникальное имя товара",
    emailNotFound: "Пользователь с указанным email не найден",
    invalidEmailFormat: "Некорректный формат email",
    invalidData: "Переданы некорректные данные",
    invalidDataValidation: "Ошибка валидации данных",
    productAlreadyInCart: "Товар уже присутствует в корзине",
    productAddedToCart: "Товар успешно добавлен в корзину",
    productNotAvailable: "Товара нет в наличии",
    productInCartNotFound: "Товар в корзине не найден",
    productDeletedFromCart: "Товар удален из корзины",
    cartIsEmpty: "Корзина пуста",
    imagesDeleted: "Изображения успешно удалены",
    videosDeleted: "Видео успешно удалены",
    internalServerError: "Произошла внутренняя ошибка сервера",
    invalidCredentials: "Неправильные почта или пароль",
    logoutSuccess: "Выход выполнен",
    loginSuccess: "Вход выполнен",
    deletedUser: "Пользователь удалён",
    hashingError: "Ошибка хеширования",
    deleteProduct: "Товар удалён",
    deleteOrder: "Заказ удален",
    productWasNotFound: "Товар не найден",
    invalidProductId: "Некорректный идентификатор товара",
    invalidFile: "Файл не передан или отсутствует MIME тип",
    fileNotExist: "Файл не существует",
    accessIsdenied: "Доступ запрещен",
    unconfirmedMail: "Почта не подтвержена, подтвердите email",
    confirmedMail: "Почта подтверждена",
    notAuthorized: "Необходима авторизация",
    passwordChanged: "Пароль успешно изменён",
    errorSendingEmail: "Ошибка отправки письма",
    sendingEmailOk: `На ваш email отправлено письмо с подтверждением регистрции. Подтвердите почту в течении ${tokenLifetimeInMinute} минут`,
    resetPasswordInstructions: 'Инструкции по сбросу пароля отправлены на ваш email', 
  };